// <auto-generated />
using System;
using CosturaProducao.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CosturaProducao.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260812164643_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CosturaProducao.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PlannedQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerPiece")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProducedQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ProductionProcessId")
                        .HasColumnType("int");

                    b.Property<int>("SeamstressId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductionProcessId");

                    b.HasIndex("SeamstressId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("CosturaProducao.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CosturaProducao.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("CosturaProducao.Models.PieceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TemplateImagePath")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PieceModels");
                });

            modelBuilder.Entity("CosturaProducao.Models.PieceService", b =>
                {
                    b.Property<int>("PieceModelId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceProcessId")
                        .HasColumnType("int");

                    b.HasKey("PieceModelId", "ServiceProcessId");

                    b.HasIndex("ServiceProcessId");

                    b.ToTable("PieceServices");
                });

            modelBuilder.Entity("CosturaProducao.Models.Production", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("PieceModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("PieceModelId");

                    b.ToTable("Productions");
                });

            modelBuilder.Entity("CosturaProducao.Models.ProductionProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PricePerPiece")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProductionId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceProcessId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductionId");

                    b.HasIndex("ServiceProcessId");

                    b.ToTable("ProductionProcesses");
                });

            modelBuilder.Entity("CosturaProducao.Models.Seamstress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Seamstresses");
                });

            modelBuilder.Entity("CosturaProducao.Models.ServiceProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DefaultPricePerPiece")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ServiceProcesses");
                });

            modelBuilder.Entity("CosturaProducao.Models.Assignment", b =>
                {
                    b.HasOne("CosturaProducao.Models.ProductionProcess", "ProductionProcess")
                        .WithMany("Assignments")
                        .HasForeignKey("ProductionProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosturaProducao.Models.Seamstress", "Seamstress")
                        .WithMany("Assignments")
                        .HasForeignKey("SeamstressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionProcess");

                    b.Navigation("Seamstress");
                });

            modelBuilder.Entity("CosturaProducao.Models.PieceService", b =>
                {
                    b.HasOne("CosturaProducao.Models.PieceModel", "PieceModel")
                        .WithMany("PieceServices")
                        .HasForeignKey("PieceModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosturaProducao.Models.ServiceProcess", "ServiceProcess")
                        .WithMany("PieceServices")
                        .HasForeignKey("ServiceProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PieceModel");

                    b.Navigation("ServiceProcess");
                });

            modelBuilder.Entity("CosturaProducao.Models.Production", b =>
                {
                    b.HasOne("CosturaProducao.Models.Client", "Client")
                        .WithMany("Productions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosturaProducao.Models.PieceModel", "PieceModel")
                        .WithMany("Productions")
                        .HasForeignKey("PieceModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("PieceModel");
                });

            modelBuilder.Entity("CosturaProducao.Models.ProductionProcess", b =>
                {
                    b.HasOne("CosturaProducao.Models.Production", "Production")
                        .WithMany("Processes")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosturaProducao.Models.ServiceProcess", "ServiceProcess")
                        .WithMany()
                        .HasForeignKey("ServiceProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Production");

                    b.Navigation("ServiceProcess");
                });

            modelBuilder.Entity("CosturaProducao.Models.Client", b =>
                {
                    b.Navigation("Productions");
                });

            modelBuilder.Entity("CosturaProducao.Models.PieceModel", b =>
                {
                    b.Navigation("PieceServices");

                    b.Navigation("Productions");
                });

            modelBuilder.Entity("CosturaProducao.Models.Production", b =>
                {
                    b.Navigation("Processes");
                });

            modelBuilder.Entity("CosturaProducao.Models.ProductionProcess", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("CosturaProducao.Models.Seamstress", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("CosturaProducao.Models.ServiceProcess", b =>
                {
                    b.Navigation("PieceServices");
                });
#pragma warning restore 612, 618
        }
    }
}
